export const USER = {
    SIGN_IN: 'USER_SIGN_IN',
    REVOKE_TOKEN: 'USER_REVOKE_TOKEN'
}

export const CONFIRMATION = {
    SHOW: 'CONFIRMATION_SHOW',
    HIDE: 'CONFIRMATION_HIDE'
}

export const NOTIFICATION = {
    SHOW: 'NOTIFICATION_SHOW',
    HIDE: 'NOTIFICATION_HIDE'
}

export const SPINNER = {
    SHOW: 'SPINNER_SHOW',
    HIDE: 'SPINNER_HIDE'
}

export default {
    USER,
    CONFIRMATION,
    NOTIFICATION,
    SPINNER
}
